### PR TITLE
104 dialect charts improvements

### PR DESCRIPTION
**Pull request by yousef337**

### CODE REVIEW

**Comment by yousef337** [comment]
The remaining part is only the labeling, chartJs does not support labels on piecharts. I am experimenting with different plugins to add support.

**Comment by zaidalyafeai** [comment]
can you pull from main that https://github.com/ARBML/masader/pull/107 is merged.

**Comment by zaidalyafeai** [comment]
> The remaining part is only the labeling, chartJs does not support labels on piecharts. I am experimenting with different plugins to add support.

Have you tried this https://stackoverflow.com/a/63822251 ?

**Comment by yousef337** [comment]
> can you pull from main that #107 is merged.

There is no need to pull from main since if this pr was merged, git will auto pull before merge.

**Comment by yousef337** [comment]
> > The remaining part is only the labeling, chartJs does not support labels on piecharts. I am experimenting with different plugins to add support.
> 
> Have you tried this https://stackoverflow.com/a/63822251 ?

The library is outdated, found a newer version that works, but had to download it and modify it to  add temporary changes to resolve some issues. I'll try to find a better solution than the existing one and gonna update you.

**Comment by zaidalyafeai** [comment]
Added some rotation to remove the overlapping. I think there is some problem with the percentages because Mauritania shouldn't be bigger than Morroco.

**Comment by yousef337** [comment]
> Added some rotation to remove the overlapping. I think there is some problem with the percentages because Mauritania shouldn't be bigger than Morroco.

Wasn't sure which one is MO and which is MR :), apparently, I've switched between them.

**Review by zaidalyafeai — APPROVED** [review]

**Pull request merged**
