### PR TITLE
Improve the UI

### PR DESCRIPTION
**Pull request by MutlaqAldhbuiub**
- Refactored the project structure and removed unused pages and scripts.
- Redesigned the pages according to the org. brand.
- Adding icon(Favicons). 

issue : #6

### CODE REVIEW

**Comment by zaidalyafeai** [comment]
Thanks, @MutlaqAldhbuiub. can you please resolve the conflicts?

**Comment by MutlaqAldhbuiub** [comment]
Thanks, @zaidalyafeai sorry 💗, I didn't pull the latest commit. 

**solved**

**Comment by zaidalyafeai** [comment]
Thanks, @MutlaqAldhbuiub. Looks good, just a few comments, 

1. please change مصدر -> مصادر. 
2. `MaxRowLength` is different in `card.js` and `index.js` which causes an error when showing the data card for the recently added datasets.

**Comment by MutlaqAldhbuiub** [comment]
> Thanks, @MutlaqAldhbuiub. Looks good, just a few comments,
> 
> 1. please change مصدر -> مصادر.
> 2. `MaxRowLength` is different in `card.js` and `index.js` which causes an error when showing the data card for the recently added datasets.

Thanks, @zaidalyafeai, and sorry for that. 

- Title has been changed from `مصدر` to `مصادر`.
- Card.js [MaxRowLength] value has been updated. 

I hope everything is good now.

**Pull request merged**
