### PR TITLE
Js fiels refactoring

### PR DESCRIPTION
**Pull request by yousef337**

### CODE REVIEW

**Comment by sudomaze** [comment]
Great work! I have two comments:
- For the `Graphs` page, the Dialect option doesn't render the graph. This happened when I moved to Jekyll even with the previous setup.
image
- For the `Explore` page, it would be nice if you can have the initial zoom to view the entire set of clusters at once rather than trying to zoom out manually.

**Comment by sudomaze** [comment]
Awesome work! Here is one last comment:

It seems that the graph in https://arbml.github.io/masader/charting.html is different than what you have.
On previous version:
image

On this branch's version:
image


I wonder if @zaidalyafeai has more context for this.

**Review by sudomaze — CHANGES_REQUESTED** [review]
Awesome work! Here is one last comment:

It seems that the graph in https://arbml.github.io/masader/charting.html is different than what you have.
On previous version:
image

On this branch's version:
image


I wonder if @zaidalyafeai has more context for this.

**Comment by zaidalyafeai** [comment]
Refarding the dialects graph, @yousef337 you need to extract the dialects info from subsets as well. I think there is an easy way to do that cc @AliOsm

**Comment by yousef337** [comment]
The problem was fixed in the last commit, I'll try to improve the introduced parts.

**Comment by yousef337** [comment]
The problem was fixed in the last commit, I'll try to improve the introduced parts.

**Review by sudomaze — APPROVED** [review]
The latest commit matches what exists in https://arbml.github.io/masader/charting.html. Great job! @yousef337

**Pull request merged**
